FROM davidegiri/esp:tutorial-micro2020-full

#
# copy over local CAD tools
#

# xilinx vivado 2019.2
COPY /opt/xilinx/Vivado/2019.2/ /opt/xilinx/Vivado/2019.2/

# mentor modelsim 2019.2
COPY /opt/mentor/modeltech /opt/mentor/modeltech

# mentor catapult hls 10.5
COPY /opt/mentor/catapult_10.5 /opt/mentor/catapult_10.5

# cadence stratus hls 18.2
COPY /opt/cadence/stratus182 /opt/cadence/stratus182

# cadence incisive 15.2
COPY /opt/cadence/incisive152 /opt/cadence/incisive152
