CUDA_PATH=/usr/local/cuda-10.0 
CUDA_LIB_PATH=/usr/local/cuda-10.0/lib64
OPENCL_PATH=/opt/intel/system_studio_2019/opencl-sdk/
OPENCL_LIB_PATH=$(OPENCL_PATH)/lib64

VISC_SRC_ROOT=$(LLVM_SRC_ROOT)

VISC_BUILD_DIR =$(VISC_SRC_ROOT)/../build
CC = $(VISC_BUILD_DIR)/bin/clang
PLATFORM_CFLAGS = -I$(LLVM_SRC_ROOT)/include -I$(VISC_BUILD_DIR)/include

CXX = $(VISC_BUILD_DIR)/bin/clang++
PLATFORM_CXXFLAGS = -I$(LLVM_SRC_ROOT)/include -I$(VISC_BUILD_DIR)/include

LINKER = $(VISC_BUILD_DIR)/bin/clang++
PLATFORM_LDFLAGS = -lm -lpthread -lrt -lOpenCL -L$(OPENCL_LIB_PATH)

LLVM_LIB_PATH = $(VISC_BUILD_DIR)/lib
LLVM_BIN_PATH = $(VISC_BUILD_DIR)/bin

OPT = $(LLVM_BIN_PATH)/opt
LLVM_LINK = $(LLVM_BIN_PATH)/llvm-link
LLVM_AS = $(LLVM_BIN_PATH)/llvm-as
LIT = $(LLVM_BIN_PATH)/llvm-lit
