# Common targets, etc. for all makefiles

OBJDIR      = obj
IT_OBJDIR   = obj_it
C_OBJDIR    = obj_c
ITC_OBJDIR  = obj_itc

OBJ_V_DIR     = obj_v
C_OBJ_V_DIR   = obj_cv

OBJ_G_DIR    = obj_gp
C_OBJ_G_DIR  = obj_cgp



# The full mini-era target, etc.
TARGET = demo-era
SRC    = src/kernels_api.c \
         src/main.c \
         src/radar/calculate_dist_from_fmcw.c \
         src/radar/octave.c \
         src/radar/timer.c \
	 src/h264/cavlc.c \
	 src/h264/decode.c \
	 src/h264/framealloc.c \
	 src/h264/interpred.c \
	 src/h264/intrapred.c \
	 src/h264/mathfunc.c \
	 src/h264/nalu.c \
	 src/h264/parset.c \
	 src/h264/residual.c \
	 src/h264/slice.c \
	 src/h264/vlc.c \
	 src/h264/do_h264_decode.c \
	 src/lz4/lz4.c \
	 src/sdr/xmit_pipe.c \
	 src/sdr/crc.c \
	 src/sdr/recv_pipe.c \
         src/sdr/complex_ops.c \
	 src/sdr/delay.c \
	 src/sdr/gr_equalizer.c \
	 src/sdr/ofdm.c \
	 src/sdr/sync_long.c \
	 src/sdr/fir.c \
	 src/sdr/sync_short.c \
	 src/sdr/sdr_viterbi.c \
	 src/sdr/descrambler_function.c \
	 src/sdr/fft.c \
	 src/read_trace.c


OBJ     = $(SRC:%.c=$(OBJDIR)/%.o)
OBJ_V   = $(SRC:%.c=$(OBJ_V_DIR)/%.o)
OBJ_G   = $(SRC:%.c=$(OBJ_G_DIR)/%.o)
IT_OBJ  = $(SRC:%.c=$(IT_OBJDIR)/%.o)
FOBJ    = $(SRC:%.c=$(OBJDIR)/%.o)
FOBJ_V  = $(SRC:%.c=$(OBJ_V_DIR)/%.o)
IT_FOBJ = $(SRC:%.c=$(IT_OBJDIR)/%.o)

#$(info $$SRC is [${SRC}])
#$(info $$SRC is [${SRC}])
#$(info $$IT_OBJDIR is [${IT_OBJDIR}])
#$(info $$IT_OBJ is [${IT_OBJ}])


# The C-code only target (it bypasses KERAS Python code)
C_TARGET = c$(TARGET)
C_OBJ    = $(SRC:%.c=$(C_OBJDIR)/%.o)
C_OBJ_V  = $(SRC:%.c=$(C_OBJ_V_DIR)/%.o)
C_OBJ_G  = $(SRC:%.c=$(C_OBJ_G_DIR)/%.o)
ITC_OBJ  = $(SRC:%.c=$(ITC_OBJDIR)/%.o)

TC_OBJ    = $(SRC:%.c=$(C_OBJDIR)/%.o)
TC_OBJ_V  = $(SRC:%.c=$(C_OBJ_V_DIR)/%.o)
TC_OBJ_G  = $(SRC!:%.c=$(C_OBJ_G_DIR)/%.o)


$(TARGET): $(OBJDIR)  $(OBJ) 
	$(CC) $(OBJ) $(CFLAGS) $(INCLUDES) $(PYTHONINCLUDES) -o $@.exe $(LFLAGS) $(LIBS) $(PYTHONLIBS)

it-$(TARGET): $(IT_OBJDIR)  $(IT_OBJ) 
	$(CC) $(IT_OBJ) $(CFLAGS) $(INCLUDES) $(PYTHONINCLUDES) -o $@.exe $(LFLAGS) $(LIBS) $(PYTHONLIBS)

f$(TARGET): $(OBJDIR)  $(OBJ) 
	$(CC) $(OBJ) $(CFLAGS) $(INCLUDES) $(PYTHONINCLUDES) -o $@.exe $(LFLAGS) $(LIBS) $(PYTHONLIBS)

it-f$(TARGET): $(OBJDIR)  $(IT_OBJ) 
	$(CC) $(IT_OBJ) $(CFLAGS) $(INCLUDES) $(PYTHONINCLUDES) -o $@.exe $(LFLAGS) $(LIBS) $(PYTHONLIBS)

$(C_TARGET): $(C_OBJDIR) $(C_OBJ) 
	$(CC) $(C_OBJ) $(CFLAGS) $(INCLUDES) $(PYTHONINCLUDES) -o $@.exe $(LFLAGS) $(LIBS) $(CPYTHONLIBS)

it-$(C_TARGET): $(ITC_OBJDIR) $(ITC_OBJ) 
	$(CC) $(ITC_OBJ) $(CFLAGS) $(INCLUDES) $(PYTHONINCLUDES) -o $@.exe $(LFLAGS) $(LIBS) $(CPYTHONLIBS)

v$(TARGET): $(OBJ_V_DIR) $(OBJ_V) 
	$(CC) $(OBJ_V) $(CFLAGS) $(INCLUDES) $(PYTHONINCLUDES) -o $@.exe $(LFLAGS) $(LIBS) $(PYTHONLIBS)

v$(C_TARGET): $(C_OBJ_V_DIR) $(C_OBJ_V) 
	$(CC) $(C_OBJ_V) $(CFLAGS) $(INCLUDES) $(PYTHONINCLUDES) -o $@.exe $(LFLAGS) $(LIBS) $(CPYTHONLIBS)



gp_$(TARGET): $(OBJ_G_DIR) $(OBJ_G) 
	$(CC) $(OBJ_G) $(CFLAGS) $(INCLUDES) $(PYTHONINCLUDES) -pg -o $@.exe $(LFLAGS) $(LIBS) $(PYTHONLIBS)

gp_$(C_TARGET): $(C_OBJ_G_DIR) $(C_OBJ_G) 
	$(CC) $(C_OBJ_G) $(CFLAGS) $(INCLUDES) $(PYTHONINCLUDES) -pg -o $@.exe $(LFLAGS) $(LIBS) $(CPYTHONLIBS)





ctrace: cobjdirs $(C_TARGET) it-$(C_TARGET) v$(C_TARGET) gp_$(C_TARGET) 

trace: objdirs $(TARGET) it-$(TARGET) v$(TARGET) gp_$(TARGET)

all: objdirs trace cver

cver: cobjdirs ctrace 

objdirs: $(OBJDIR) $(IT_OBJDIR) $(OBJ_V_DIR) $(OBJ_G_DIR) 

cobjdirs: $(C_OBJDIR) $(ITC_OBJDIR) $(C_OBJ_V_DIR) $(C_OBJ_G_DIR)



util_prog:
	cd utils; make -f $(MFILE) all

test: 
	cd utils; make -f $(MFILE) test

vtest: 
	cd utils; make -f $(MFILE) vtest

tracegen: 
	cd utils; make -f $(MFILE) tracegen



$(OBJDIR):
	mkdir $@
	mkdir -p $@/src/radar
	mkdir -p $@/src/h264
	mkdir -p $@/src/lz4
	mkdir -p $@/src/sdr

$(IT_OBJDIR):
	mkdir $@
	mkdir -p $@/src/radar
	mkdir -p $@/src/h264
	mkdir -p $@/src/lz4
	mkdir -p $@/src/sdr

$(C_OBJDIR):
	mkdir $@
	mkdir -p $@/src/radar
	mkdir -p $@/src/h264
	mkdir -p $@/src/lz4
	mkdir -p $@/src/sdr

$(ITC_OBJDIR):
	mkdir $@
	mkdir -p $@/src/radar
	mkdir -p $@/src/h264
	mkdir -p $@/src/lz4
	mkdir -p $@/src/sdr

$(OBJ_V_DIR):
	mkdir $@
	mkdir -p $@/src/radar
	mkdir -p $@/src/h264
	mkdir -p $@/src/lz4
	mkdir -p $@/src/sdr

$(T_OBJ_V_DIR):
	mkdir $@
	mkdir -p $@/src/radar
	mkdir -p $@/src/h264
	mkdir -p $@/src/lz4
	mkdir -p $@/src/sdr

$(C_OBJ_V_DIR):
	mkdir $@
	mkdir -p $@/src/radar
	mkdir -p $@/src/h264
	mkdir -p $@/src/lz4
	mkdir -p $@/src/sdr

$(OBJ_G_DIR):
	mkdir $@
	mkdir -p $@/src/radar
	mkdir -p $@/src/h264
	mkdir -p $@/src/lz4
	mkdir -p $@/src/sdr

$(C_OBJ_G_DIR):
	mkdir $@	
	mkdir -p $@/src/radar
	mkdir -p $@/src/h264
	mkdir -p $@/src/lz4
	mkdir -p $@/src/sdr




$(OBJDIR)/%.o: %.c
	$(CC) $(CFLAGS) $(PYTHONINCLUDES) -o $@ $(PYTHONLIBS) -c $<

$(T_OBJDIR)/%.o: %.c
	$(CC) $(CFLAGS) $(PYTHONINCLUDES) -o $@ $(PYTHONLIBS) -c $<

$(IT_OBJDIR)/%.o: %.c
	$(CC) $(CFLAGS) $(PYTHONINCLUDES) -DINT_TIME -o $@ $(PYTHONLIBS) -c $<

$(C_OBJDIR)/%.o: %.c
	$(CC) $(CFLAGS) $(PYTHONINCLUDES) -DBYPASS_KERAS_CV_CODE -o $@ $(PYTHONLIBS) -c $<

$(TC_OBJDIR)/%.o: %.c
	$(CC) $(CFLAGS) $(PYTHONINCLUDES) -DINT_TIME -DBYPASS_KERAS_CV_CODE -o $@ $(PYTHONLIBS) -c $<

$(ITC_OBJDIR)/%.o: %.c
	$(CC) $(CFLAGS) $(PYTHONINCLUDES) -DINT_TIME -DBYPASS_KERAS_CV_CODE -o $@ $(PYTHONLIBS) -c $<

$(OBJ_V_DIR)/%.o: %.c
	$(CC) $(CFLAGS) $(PYTHONINCLUDES) -DDEBUG_MODE -o $@ $(PYTHONLIBS) -c $<

$(C_OBJ_V_DIR)/%.o: %.c
	$(CC) $(CFLAGS) $(PYTHONINCLUDES) -DDEBUG_MODE -DBYPASS_KERAS_CV_CODE -o $@ $(PYTHONLIBS) -c $<

$(OBJ_G_DIR)/%.o: %.c
	$(CC) $(CFLAGS) $(PYTHONINCLUDES) -g -pg -o $@ $(PYTHONLIBS) -c $<

$(C_OBJ_G_DIR)/%.o: %.c
	$(CC) $(CFLAGS) $(PYTHONINCLUDES) -DBYPASS_KERAS_CV_CODE -g -pg -o $@ $(PYTHONLIBS) -c $<







clean:
	$(RM) $(TARGET).exe $(OBJ)
	$(RM) it-$(TARGET).exe $(IT_OBJ)
	$(RM) $(C_TARGET).exe $(C_OBJ)
	$(RM) it-$(C_TARGET).exe $(ITC_OBJ)
	$(RM) v$(TARGET).exe $(OBJ_V)
	$(RM) v$(C_TARGET).exe $(C_OBJ_V)
	$(RM) gp_$(TARGET).exe $(OBJ_G)
	$(RM) gp_$(C_TARGET).exe $(C_OBJ_G)

clobber: clean
	$(RM) -rf $(OBJDIR) $(IT_OBJDIR)
	$(RM) -rf $(C_OBJDIR) $(ITC_OBJDIR)
	$(RM) -rf $(OBJ_V_DIR) $(C_OBJ_V_DIR)
	$(RM) -rf $(OBJ_G_DIR) $(C_OBJ_G_DIR)

allclean: clobber



$(OBJDIR)/main.o: include/kernels_api.h
$(OBJDIR)/kernels_api.o: include/kernels_api.h
$(OBJDIR)/kernels_api.o: include/read_trace.h
$(OBJDIR)/kernels_api.o: include/radar/calc_fmcw_dist.h
$(OBJDIR)/read_trace.o: include/kernels_api.h
$(OBJDIR)/read_trace.o: include/read_trace.h
$(OBJDIR)/h264/cavlc.o: include/h264/global.h
$(OBJDIR)/h264/cavlc.o: include/h264/vlc.h
$(OBJDIR)/h264/decode.o: include/h264/global.h 
$(OBJDIR)/h264/decode.o: include/h264/parset.h 
$(OBJDIR)/h264/decode.o: include/h264/decode.h 
$(OBJDIR)/h264/decode.o: include/h264/slice.h
$(OBJDIR)/h264/framealloc.o: include/h264/global.h 
$(OBJDIR)/h264/interpred.o: include/h264/global.h 
$(OBJDIR)/h264/interpred.o: include/h264/vlc.h 
$(OBJDIR)/h264/interpred.o: include/h264/mathfunc.h
$(OBJDIR)/h264/mathfunc.o: include/h264/global.h
$(OBJDIR)/h264/mathfunc.o: include/h264/mathfunc.h
$(OBJDIR)/h264/nalu.o: include/h264/global.h
$(OBJDIR)/h264/parset.o: include/h264/global.h
$(OBJDIR)/h264/parset.o: include/h264/framealloc.h
$(OBJDIR)/h264/parset.o: include/h264/vlc.h
$(OBJDIR)/h264/residual.o: include/h264/global.h 
$(OBJDIR)/h264/slice.o: include/h264/global.h
$(OBJDIR)/h264/slice.o: include/h264/intrapred.h
$(OBJDIR)/h264/slice.o: include/h264/vlc.h
$(OBJDIR)/h264/slice.o: include/h264/cavlc.h
$(OBJDIR)/h264/slice.o: include/h264/mathfunc.h
$(OBJDIR)/h264/slice.o: include/h264/residual.h
$(OBJDIR)/h264/slice.o: include/h264/interpred.h
$(OBJDIR)/h264/vlc.o: include/h264/global.h
$(OBJDIR)/h264/do_h264_decode.o: h264/global.h 
$(OBJDIR)/h264/do_h264_decode.o: include/h264/nalu.h 
$(OBJDIR)/h264/do_h264_decode.o: include/h264/decode.h
$(OBJDIR)/lv4/lv4.o: include/lv4/lv4.h
$(OBJDIR)/sdr/xmit_pipe.o: include/sdr/debug.h
$(OBJDIR)/sdr/xmit_pipe.o: include/sdr/base.h
$(OBJDIR)/sdr/xmit_pipe.o: include/sdr/xmit_pipe.h
$(OBJDIR)/sdr/xmit_pipe.o: include/sdr/fft.h
$(OBJDIR)/sdr/xmit_pipe.o: include/sdr/crc.h
$(OBJDIR)/sdr/crc.o: include/sdr/crc.h
$(OBJDIR)/sdr/recv_pipe.o: include/sdr/debug.h
$(OBJDIR)/sdr/recv_pipe.o: include/sdr/type.h
$(OBJDIR)/sdr/recv_pipe.o: include/sdr/base.h
$(OBJDIR)/sdr/recv_pipe.o: include/sdr/delay.h
$(OBJDIR)/sdr/recv_pipe.o: include/sdr/complex_ops.h
$(OBJDIR)/sdr/recv_pipe.o: include/sdr/fir.h
$(OBJDIR)/sdr/recv_pipe.o: include/sdr/sync_short.h
$(OBJDIR)/sdr/recv_pipe.o: include/sdr/sync_long.h
$(OBJDIR)/sdr/recv_pipe.o: include/sdr/gr_equalizer.h
$(OBJDIR)/sdr/recv_pipe.o: include/sdr/ofdm.h
$(OBJDIR)/sdr/recv_pipe.o: include/sdr/recv_pipe.h
$(OBJDIR)/sdr/recv_pipe.o: include/sdr/recv_pipe.h
$(OBJDIR)/sdr/complex_ops.o: include/sdr/complex_ops.h
$(OBJDIR)/sdr/complex_ops.o: include/sdr/type.h
$(OBJDIR)/sdr/complex_ops.o: include/sdr/base.h
$(OBJDIR)/sdr/delay.o: include/sdr/debug.h
$(OBJDIR)/sdr/delay.o: include/sdr/delay.h
$(OBJDIR)/sdr/delay.o: include/sdr/type.h
$(OBJDIR)/sdr/delay.o: include/sdr/base.h
$(OBJDIR)/sdr/gr_equalizer.o: include/sdr/debug.h
$(OBJDIR)/sdr/gr_equalizer.o: include/sdr/type.h
$(OBJDIR)/sdr/gr_equalizer.o: include/sdr/base.h
$(OBJDIR)/sdr/gr_equalizer.o: include/sdr/sdr_viterbi.h
$(OBJDIR)/sdr/gr_equalizer.o: include/sdr/gr_equalizer.h
$(OBJDIR)/sdr/ofdm.o: include/sdr/debug.h
$(OBJDIR)/sdr/ofdm.o: include/sdr/type.h
$(OBJDIR)/sdr/ofdm.o: include/sdr/base.h
$(OBJDIR)/sdr/ofdm.o: include/sdr/ofdm.h
$(OBJDIR)/sdr/ofdm.o: include/sdr/sdr_viterbi.h
$(OBJDIR)/sdr/sync_long.o: include/sdr/debug.h
$(OBJDIR)/sdr/sync_long.o: include/sdr/complex_ops.h
$(OBJDIR)/sdr/sync_long.o: include/sdr/type.h
$(OBJDIR)/sdr/sync_long.o: include/sdr/base.h
$(OBJDIR)/sdr/sync_long.o: include/sdr/sync_long.h
$(OBJDIR)/sdr/fir.o: include/sdr/debug.h
$(OBJDIR)/sdr/fir.o: include/sdr/type.h
$(OBJDIR)/sdr/fir.o: include/sdr/sync_short.h
$(OBJDIR)/sdr/fir.o: include/sdr/base.h
$(OBJDIR)/sdr/fir.o: include/sdr/fir.h
$(OBJDIR)/sdr/sync_short.o: include/sdr/debug.h
$(OBJDIR)/sdr/sync_short.o: include/sdr/sync_short.h
$(OBJDIR)/sdr/sync_short.o: include/sdr/type.h
$(OBJDIR)/sdr/sync_short.o: include/sdr/base.h
$(OBJDIR)/sdr/sdr_viterbi.o: include/sdr/debug.h 
$(OBJDIR)/sdr/sdr_viterbi.o: include/sdr/base.h 
$(OBJDIR)/sdr/sdr_viterbi.o: include/sdr/sdr_viterbi.h
$(OBJDIR)/sdr/descrambler_function.o: include/sdr/debug.h 
$(OBJDIR)/sdr/descrambler_function.o: include/sdr/base.h
$(OBJDIR)/sdr/simple_dft.o: include/sdr/debug.h
$(OBJDIR)/sdr/simple_dft.o: include/sdr/simple_dft.h
$(OBJDIR)/sdr/fft.o: include/sdr/fft.h
$(OBJDIR)/sdr/fft.o: include/sdr/debug.h

$(C_OBJDIR)/main.o: include/kernels_api.h
$(C_OBJDIR)/kernels_api.o: include/kernels_api.h
$(C_OBJDIR)/kernels_api.o: include/read_trace.h
$(C_OBJDIR)/kernels_api.o: include/radar/calc_fmcw_dist.h
$(C_OBJDIR)/read_trace.o: include/kernels_api.h
$(C_OBJDIR)/read_trace.o: include/read_trace.h
$(C_OBJDIR)/h264/cavlc.o: include/h264/global.h
$(C_OBJDIR)/h264/cavlc.o: include/h264/vlc.h
$(C_OBJDIR)/h264/decode.o: include/h264/global.h 
$(C_OBJDIR)/h264/decode.o: include/h264/parset.h 
$(C_OBJDIR)/h264/decode.o: include/h264/decode.h 
$(C_OBJDIR)/h264/decode.o: include/h264/slice.h
$(C_OBJDIR)/h264/framealloc.o: include/h264/global.h 
$(C_OBJDIR)/h264/interpred.o: include/h264/global.h 
$(C_OBJDIR)/h264/interpred.o: include/h264/vlc.h 
$(C_OBJDIR)/h264/interpred.o: include/h264/mathfunc.h
$(C_OBJDIR)/h264/mathfunc.o: include/h264/global.h
$(C_OBJDIR)/h264/mathfunc.o: include/h264/mathfunc.h
$(C_OBJDIR)/h264/nalu.o: include/h264/global.h
$(C_OBJDIR)/h264/parset.o: include/h264/global.h
$(C_OBJDIR)/h264/parset.o: include/h264/framealloc.h
$(C_OBJDIR)/h264/parset.o: include/h264/vlc.h
$(C_OBJDIR)/h264/residual.o: include/h264/global.h 
$(C_OBJDIR)/h264/slice.o: include/h264/global.h
$(C_OBJDIR)/h264/slice.o: include/h264/intrapred.h
$(C_OBJDIR)/h264/slice.o: include/h264/vlc.h
$(C_OBJDIR)/h264/slice.o: include/h264/cavlc.h
$(C_OBJDIR)/h264/slice.o: include/h264/mathfunc.h
$(C_OBJDIR)/h264/slice.o: include/h264/residual.h
$(C_OBJDIR)/h264/slice.o: include/h264/interpred.h
$(C_OBJDIR)/h264/vlc.o: include/h264/global.h
$(C_OBJDIR)/h264/do_h264_decode.o: h264/global.h 
$(C_OBJDIR)/h264/do_h264_decode.o: include/h264/nalu.h 
$(C_OBJDIR)/h264/do_h264_decode.o: include/h264/decode.h
$(C_OBJDIR)/lv4/lv4.o: include/lv4/lv4.h
$(C_OBJDIR)/sdr/xmit_pipe.o: include/sdr/debug.h
$(C_OBJDIR)/sdr/xmit_pipe.o: include/sdr/base.h
$(C_OBJDIR)/sdr/xmit_pipe.o: include/sdr/xmit_pipe.h
$(C_OBJDIR)/sdr/xmit_pipe.o: include/sdr/fft.h
$(C_OBJDIR)/sdr/xmit_pipe.o: include/sdr/crc.h
$(C_OBJDIR)/sdr/crc.o: include/sdr/crc.h
$(C_OBJDIR)/sdr/recv_pipe.o: include/sdr/debug.h
$(C_OBJDIR)/sdr/recv_pipe.o: include/sdr/type.h
$(C_OBJDIR)/sdr/recv_pipe.o: include/sdr/base.h
$(C_OBJDIR)/sdr/recv_pipe.o: include/sdr/delay.h
$(C_OBJDIR)/sdr/recv_pipe.o: include/sdr/complex_ops.h
$(C_OBJDIR)/sdr/recv_pipe.o: include/sdr/fir.h
$(C_OBJDIR)/sdr/recv_pipe.o: include/sdr/sync_short.h
$(C_OBJDIR)/sdr/recv_pipe.o: include/sdr/sync_long.h
$(C_OBJDIR)/sdr/recv_pipe.o: include/sdr/gr_equalizer.h
$(C_OBJDIR)/sdr/recv_pipe.o: include/sdr/ofdm.h
$(C_OBJDIR)/sdr/recv_pipe.o: include/sdr/recv_pipe.h
$(C_OBJDIR)/sdr/recv_pipe.o: include/sdr/recv_pipe.h
$(C_OBJDIR)/sdr/complex_ops.o: include/sdr/complex_ops.h
$(C_OBJDIR)/sdr/complex_ops.o: include/sdr/type.h
$(C_OBJDIR)/sdr/complex_ops.o: include/sdr/base.h
$(C_OBJDIR)/sdr/delay.o: include/sdr/debug.h
$(C_OBJDIR)/sdr/delay.o: include/sdr/delay.h
$(C_OBJDIR)/sdr/delay.o: include/sdr/type.h
$(C_OBJDIR)/sdr/delay.o: include/sdr/base.h
$(C_OBJDIR)/sdr/gr_equalizer.o: include/sdr/debug.h
$(C_OBJDIR)/sdr/gr_equalizer.o: include/sdr/type.h
$(C_OBJDIR)/sdr/gr_equalizer.o: include/sdr/base.h
$(C_OBJDIR)/sdr/gr_equalizer.o: include/sdr/sdr_viterbi.h
$(C_OBJDIR)/sdr/gr_equalizer.o: include/sdr/gr_equalizer.h
$(C_OBJDIR)/sdr/ofdm.o: include/sdr/debug.h
$(C_OBJDIR)/sdr/ofdm.o: include/sdr/type.h
$(C_OBJDIR)/sdr/ofdm.o: include/sdr/base.h
$(C_OBJDIR)/sdr/ofdm.o: include/sdr/ofdm.h
$(C_OBJDIR)/sdr/ofdm.o: include/sdr/sdr_viterbi.h
$(C_OBJDIR)/sdr/sync_long.o: include/sdr/debug.h
$(C_OBJDIR)/sdr/sync_long.o: include/sdr/complex_ops.h
$(C_OBJDIR)/sdr/sync_long.o: include/sdr/type.h
$(C_OBJDIR)/sdr/sync_long.o: include/sdr/base.h
$(C_OBJDIR)/sdr/sync_long.o: include/sdr/sync_long.h
$(C_OBJDIR)/sdr/fir.o: include/sdr/debug.h
$(C_OBJDIR)/sdr/fir.o: include/sdr/type.h
$(C_OBJDIR)/sdr/fir.o: include/sdr/sync_short.h
$(C_OBJDIR)/sdr/fir.o: include/sdr/base.h
$(C_OBJDIR)/sdr/fir.o: include/sdr/fir.h
$(C_OBJDIR)/sdr/sync_short.o: include/sdr/debug.h
$(C_OBJDIR)/sdr/sync_short.o: include/sdr/sync_short.h
$(C_OBJDIR)/sdr/sync_short.o: include/sdr/type.h
$(C_OBJDIR)/sdr/sync_short.o: include/sdr/base.h
$(C_OBJDIR)/sdr/sdr_viterbi.o: include/sdr/debug.h 
$(C_OBJDIR)/sdr/sdr_viterbi.o: include/sdr/base.h 
$(C_OBJDIR)/sdr/sdr_viterbi.o: include/sdr/sdr_viterbi.h
$(C_OBJDIR)/sdr/descrambler_function.o: include/sdr/debug.h 
$(C_OBJDIR)/sdr/descrambler_function.o: include/sdr/base.h
$(C_OBJDIR)/sdr/simple_dft.o: include/sdr/debug.h
$(C_OBJDIR)/sdr/simple_dft.o: include/sdr/simple_dft.h
$(C_OBJDIR)/sdr/fft.o: include/sdr/fft.h
$(C_OBJDIR)/sdr/fft.o: include/sdr/debug.h

$(OBJ_V_DIR)/main.o: include/kernels_api.h
$(OBJ_V_DIR)/kernels_api.o: include/kernels_api.h
$(OBJ_V_DIR)/kernels_api.o: include/read_trace.h
$(OBJ_V_DIR)/kernels_api.o: include/radar/calc_fmcw_dist.h
$(OBJ_V_DIR)/read_trace.o: include/kernels_api.h
$(OBJ_V_DIR)/read_trace.o: include/read_trace.h
$(OBJ_V_DIR)/h264/cavlc.o: include/h264/global.h
$(OBJ_V_DIR)/h264/cavlc.o: include/h264/vlc.h
$(OBJ_V_DIR)/h264/decode.o: include/h264/global.h 
$(OBJ_V_DIR)/h264/decode.o: include/h264/parset.h 
$(OBJ_V_DIR)/h264/decode.o: include/h264/decode.h 
$(OBJ_V_DIR)/h264/decode.o: include/h264/slice.h
$(OBJ_V_DIR)/h264/framealloc.o: include/h264/global.h 
$(OBJ_V_DIR)/h264/interpred.o: include/h264/global.h 
$(OBJ_V_DIR)/h264/interpred.o: include/h264/vlc.h 
$(OBJ_V_DIR)/h264/interpred.o: include/h264/mathfunc.h
$(OBJ_V_DIR)/h264/mathfunc.o: include/h264/global.h
$(OBJ_V_DIR)/h264/mathfunc.o: include/h264/mathfunc.h
$(OBJ_V_DIR)/h264/nalu.o: include/h264/global.h
$(OBJ_V_DIR)/h264/parset.o: include/h264/global.h
$(OBJ_V_DIR)/h264/parset.o: include/h264/framealloc.h
$(OBJ_V_DIR)/h264/parset.o: include/h264/vlc.h
$(OBJ_V_DIR)/h264/residual.o: include/h264/global.h 
$(OBJ_V_DIR)/h264/slice.o: include/h264/global.h
$(OBJ_V_DIR)/h264/slice.o: include/h264/intrapred.h
$(OBJ_V_DIR)/h264/slice.o: include/h264/vlc.h
$(OBJ_V_DIR)/h264/slice.o: include/h264/cavlc.h
$(OBJ_V_DIR)/h264/slice.o: include/h264/mathfunc.h
$(OBJ_V_DIR)/h264/slice.o: include/h264/residual.h
$(OBJ_V_DIR)/h264/slice.o: include/h264/interpred.h
$(OBJ_V_DIR)/h264/vlc.o: include/h264/global.h
$(OBJ_V_DIR)/h264/do_h264_decode.o: h264/global.h 
$(OBJ_V_DIR)/h264/do_h264_decode.o: include/h264/nalu.h 
$(OBJ_V_DIR)/h264/do_h264_decode.o: include/h264/decode.h
$(OBJ_V_DIR)/lv4/lv4.o: include/lv4/lv4.h
$(OBJ_V_DIR)/sdr/xmit_pipe.o: include/sdr/debug.h
$(OBJ_V_DIR)/sdr/xmit_pipe.o: include/sdr/base.h
$(OBJ_V_DIR)/sdr/xmit_pipe.o: include/sdr/xmit_pipe.h
$(OBJ_V_DIR)/sdr/xmit_pipe.o: include/sdr/fft.h
$(OBJ_V_DIR)/sdr/xmit_pipe.o: include/sdr/crc.h
$(OBJ_V_DIR)/sdr/crc.o: include/sdr/crc.h
$(OBJ_V_DIR)/sdr/recv_pipe.o: include/sdr/debug.h
$(OBJ_V_DIR)/sdr/recv_pipe.o: include/sdr/type.h
$(OBJ_V_DIR)/sdr/recv_pipe.o: include/sdr/base.h
$(OBJ_V_DIR)/sdr/recv_pipe.o: include/sdr/delay.h
$(OBJ_V_DIR)/sdr/recv_pipe.o: include/sdr/complex_ops.h
$(OBJ_V_DIR)/sdr/recv_pipe.o: include/sdr/fir.h
$(OBJ_V_DIR)/sdr/recv_pipe.o: include/sdr/sync_short.h
$(OBJ_V_DIR)/sdr/recv_pipe.o: include/sdr/sync_long.h
$(OBJ_V_DIR)/sdr/recv_pipe.o: include/sdr/gr_equalizer.h
$(OBJ_V_DIR)/sdr/recv_pipe.o: include/sdr/ofdm.h
$(OBJ_V_DIR)/sdr/recv_pipe.o: include/sdr/recv_pipe.h
$(OBJ_V_DIR)/sdr/recv_pipe.o: include/sdr/recv_pipe.h
$(OBJ_V_DIR)/sdr/complex_ops.o: include/sdr/complex_ops.h
$(OBJ_V_DIR)/sdr/complex_ops.o: include/sdr/type.h
$(OBJ_V_DIR)/sdr/complex_ops.o: include/sdr/base.h
$(OBJ_V_DIR)/sdr/delay.o: include/sdr/debug.h
$(OBJ_V_DIR)/sdr/delay.o: include/sdr/delay.h
$(OBJ_V_DIR)/sdr/delay.o: include/sdr/type.h
$(OBJ_V_DIR)/sdr/delay.o: include/sdr/base.h
$(OBJ_V_DIR)/sdr/gr_equalizer.o: include/sdr/debug.h
$(OBJ_V_DIR)/sdr/gr_equalizer.o: include/sdr/type.h
$(OBJ_V_DIR)/sdr/gr_equalizer.o: include/sdr/base.h
$(OBJ_V_DIR)/sdr/gr_equalizer.o: include/sdr/sdr_viterbi.h
$(OBJ_V_DIR)/sdr/gr_equalizer.o: include/sdr/gr_equalizer.h
$(OBJ_V_DIR)/sdr/ofdm.o: include/sdr/debug.h
$(OBJ_V_DIR)/sdr/ofdm.o: include/sdr/type.h
$(OBJ_V_DIR)/sdr/ofdm.o: include/sdr/base.h
$(OBJ_V_DIR)/sdr/ofdm.o: include/sdr/ofdm.h
$(OBJ_V_DIR)/sdr/ofdm.o: include/sdr/sdr_viterbi.h
$(OBJ_V_DIR)/sdr/sync_long.o: include/sdr/debug.h
$(OBJ_V_DIR)/sdr/sync_long.o: include/sdr/complex_ops.h
$(OBJ_V_DIR)/sdr/sync_long.o: include/sdr/type.h
$(OBJ_V_DIR)/sdr/sync_long.o: include/sdr/base.h
$(OBJ_V_DIR)/sdr/sync_long.o: include/sdr/sync_long.h
$(OBJ_V_DIR)/sdr/fir.o: include/sdr/debug.h
$(OBJ_V_DIR)/sdr/fir.o: include/sdr/type.h
$(OBJ_V_DIR)/sdr/fir.o: include/sdr/sync_short.h
$(OBJ_V_DIR)/sdr/fir.o: include/sdr/base.h
$(OBJ_V_DIR)/sdr/fir.o: include/sdr/fir.h
$(OBJ_V_DIR)/sdr/sync_short.o: include/sdr/debug.h
$(OBJ_V_DIR)/sdr/sync_short.o: include/sdr/sync_short.h
$(OBJ_V_DIR)/sdr/sync_short.o: include/sdr/type.h
$(OBJ_V_DIR)/sdr/sync_short.o: include/sdr/base.h
$(OBJ_V_DIR)/sdr/sdr_viterbi.o: include/sdr/debug.h 
$(OBJ_V_DIR)/sdr/sdr_viterbi.o: include/sdr/base.h 
$(OBJ_V_DIR)/sdr/sdr_viterbi.o: include/sdr/sdr_viterbi.h
$(OBJ_V_DIR)/sdr/descrambler_function.o: include/sdr/debug.h 
$(OBJ_V_DIR)/sdr/descrambler_function.o: include/sdr/base.h
$(OBJ_V_DIR)/sdr/simple_dft.o: include/sdr/debug.h
$(OBJ_V_DIR)/sdr/simple_dft.o: include/sdr/simple_dft.h
$(OBJ_V_DIR)/sdr/fft.o: include/sdr/fft.h
$(OBJ_V_DIR)/sdr/fft.o: include/sdr/debug.h

$(C_OBJ_V_DIR)/main.o: include/kernels_api.h
$(C_OBJ_V_DIR)/kernels_api.o: include/kernels_api.h
$(C_OBJ_V_DIR)/kernels_api.o: include/read_trace.h
$(C_OBJ_V_DIR)/kernels_api.o: include/radar/calc_fmcw_dist.h
$(C_OBJ_V_DIR)/read_trace.o: include/kernels_api.h
$(C_OBJ_V_DIR)/read_trace.o: include/read_trace.h
$(C_OBJ_V_DIR)/h264/cavlc.o: include/h264/global.h
$(C_OBJ_V_DIR)/h264/cavlc.o: include/h264/vlc.h
$(C_OBJ_V_DIR)/h264/decode.o: include/h264/global.h 
$(C_OBJ_V_DIR)/h264/decode.o: include/h264/parset.h 
$(C_OBJ_V_DIR)/h264/decode.o: include/h264/decode.h 
$(C_OBJ_V_DIR)/h264/decode.o: include/h264/slice.h
$(C_OBJ_V_DIR)/h264/framealloc.o: include/h264/global.h 
$(C_OBJ_V_DIR)/h264/interpred.o: include/h264/global.h 
$(C_OBJ_V_DIR)/h264/interpred.o: include/h264/vlc.h 
$(C_OBJ_V_DIR)/h264/interpred.o: include/h264/mathfunc.h
$(C_OBJ_V_DIR)/h264/mathfunc.o: include/h264/global.h
$(C_OBJ_V_DIR)/h264/mathfunc.o: include/h264/mathfunc.h
$(C_OBJ_V_DIR)/h264/nalu.o: include/h264/global.h
$(C_OBJ_V_DIR)/h264/parset.o: include/h264/global.h
$(C_OBJ_V_DIR)/h264/parset.o: include/h264/framealloc.h
$(C_OBJ_V_DIR)/h264/parset.o: include/h264/vlc.h
$(C_OBJ_V_DIR)/h264/residual.o: include/h264/global.h 
$(C_OBJ_V_DIR)/h264/slice.o: include/h264/global.h
$(C_OBJ_V_DIR)/h264/slice.o: include/h264/intrapred.h
$(C_OBJ_V_DIR)/h264/slice.o: include/h264/vlc.h
$(C_OBJ_V_DIR)/h264/slice.o: include/h264/cavlc.h
$(C_OBJ_V_DIR)/h264/slice.o: include/h264/mathfunc.h
$(C_OBJ_V_DIR)/h264/slice.o: include/h264/residual.h
$(C_OBJ_V_DIR)/h264/slice.o: include/h264/interpred.h
$(C_OBJ_V_DIR)/h264/vlc.o: include/h264/global.h
$(C_OBJ_V_DIR)/h264/do_h264_decode.o: h264/global.h 
$(C_OBJ_V_DIR)/h264/do_h264_decode.o: include/h264/nalu.h 
$(C_OBJ_V_DIR)/h264/do_h264_decode.o: include/h264/decode.h
$(C_OBJ_V_DIR)/lv4/lv4.o: include/lv4/lv4.h
$(C_OBJ_V_DIR)/sdr/xmit_pipe.o: include/sdr/debug.h
$(C_OBJ_V_DIR)/sdr/xmit_pipe.o: include/sdr/base.h
$(C_OBJ_V_DIR)/sdr/xmit_pipe.o: include/sdr/xmit_pipe.h
$(C_OBJ_V_DIR)/sdr/xmit_pipe.o: include/sdr/fft.h
$(C_OBJ_V_DIR)/sdr/xmit_pipe.o: include/sdr/crc.h
$(C_OBJ_V_DIR)/sdr/crc.o: include/sdr/crc.h
$(C_OBJ_V_DIR)/sdr/recv_pipe.o: include/sdr/debug.h
$(C_OBJ_V_DIR)/sdr/recv_pipe.o: include/sdr/type.h
$(C_OBJ_V_DIR)/sdr/recv_pipe.o: include/sdr/base.h
$(C_OBJ_V_DIR)/sdr/recv_pipe.o: include/sdr/delay.h
$(C_OBJ_V_DIR)/sdr/recv_pipe.o: include/sdr/complex_ops.h
$(C_OBJ_V_DIR)/sdr/recv_pipe.o: include/sdr/fir.h
$(C_OBJ_V_DIR)/sdr/recv_pipe.o: include/sdr/sync_short.h
$(C_OBJ_V_DIR)/sdr/recv_pipe.o: include/sdr/sync_long.h
$(C_OBJ_V_DIR)/sdr/recv_pipe.o: include/sdr/gr_equalizer.h
$(C_OBJ_V_DIR)/sdr/recv_pipe.o: include/sdr/ofdm.h
$(C_OBJ_V_DIR)/sdr/recv_pipe.o: include/sdr/recv_pipe.h
$(C_OBJ_V_DIR)/sdr/recv_pipe.o: include/sdr/recv_pipe.h
$(C_OBJ_V_DIR)/sdr/complex_ops.o: include/sdr/complex_ops.h
$(C_OBJ_V_DIR)/sdr/complex_ops.o: include/sdr/type.h
$(C_OBJ_V_DIR)/sdr/complex_ops.o: include/sdr/base.h
$(C_OBJ_V_DIR)/sdr/delay.o: include/sdr/debug.h
$(C_OBJ_V_DIR)/sdr/delay.o: include/sdr/delay.h
$(C_OBJ_V_DIR)/sdr/delay.o: include/sdr/type.h
$(C_OBJ_V_DIR)/sdr/delay.o: include/sdr/base.h
$(C_OBJ_V_DIR)/sdr/gr_equalizer.o: include/sdr/debug.h
$(C_OBJ_V_DIR)/sdr/gr_equalizer.o: include/sdr/type.h
$(C_OBJ_V_DIR)/sdr/gr_equalizer.o: include/sdr/base.h
$(C_OBJ_V_DIR)/sdr/gr_equalizer.o: include/sdr/sdr_viterbi.h
$(C_OBJ_V_DIR)/sdr/gr_equalizer.o: include/sdr/gr_equalizer.h
$(C_OBJ_V_DIR)/sdr/ofdm.o: include/sdr/debug.h
$(C_OBJ_V_DIR)/sdr/ofdm.o: include/sdr/type.h
$(C_OBJ_V_DIR)/sdr/ofdm.o: include/sdr/base.h
$(C_OBJ_V_DIR)/sdr/ofdm.o: include/sdr/ofdm.h
$(C_OBJ_V_DIR)/sdr/ofdm.o: include/sdr/sdr_viterbi.h
$(C_OBJ_V_DIR)/sdr/sync_long.o: include/sdr/debug.h
$(C_OBJ_V_DIR)/sdr/sync_long.o: include/sdr/complex_ops.h
$(C_OBJ_V_DIR)/sdr/sync_long.o: include/sdr/type.h
$(C_OBJ_V_DIR)/sdr/sync_long.o: include/sdr/base.h
$(C_OBJ_V_DIR)/sdr/sync_long.o: include/sdr/sync_long.h
$(C_OBJ_V_DIR)/sdr/fir.o: include/sdr/debug.h
$(C_OBJ_V_DIR)/sdr/fir.o: include/sdr/type.h
$(C_OBJ_V_DIR)/sdr/fir.o: include/sdr/sync_short.h
$(C_OBJ_V_DIR)/sdr/fir.o: include/sdr/base.h
$(C_OBJ_V_DIR)/sdr/fir.o: include/sdr/fir.h
$(C_OBJ_V_DIR)/sdr/sync_short.o: include/sdr/debug.h
$(C_OBJ_V_DIR)/sdr/sync_short.o: include/sdr/sync_short.h
$(C_OBJ_V_DIR)/sdr/sync_short.o: include/sdr/type.h
$(C_OBJ_V_DIR)/sdr/sync_short.o: include/sdr/base.h
$(C_OBJ_V_DIR)/sdr/sdr_viterbi.o: include/sdr/debug.h 
$(C_OBJ_V_DIR)/sdr/sdr_viterbi.o: include/sdr/base.h 
$(C_OBJ_V_DIR)/sdr/sdr_viterbi.o: include/sdr/sdr_viterbi.h
$(C_OBJ_V_DIR)/sdr/descrambler_function.o: include/sdr/debug.h 
$(C_OBJ_V_DIR)/sdr/descrambler_function.o: include/sdr/base.h
$(C_OBJ_V_DIR)/sdr/simple_dft.o: include/sdr/debug.h
$(C_OBJ_V_DIR)/sdr/simple_dft.o: include/sdr/simple_dft.h
$(C_OBJ_V_DIR)/sdr/fft.o: include/sdr/fft.h
$(C_OBJ_V_DIR)/sdr/fft.o: include/sdr/debug.h


$(OBJ_G_DIR)/main.o: include/kernels_api.h
$(OBJ_G_DIR)/kernels_api.o: include/kernels_api.h
$(OBJ_G_DIR)/kernels_api.o: include/read_trace.h
$(OBJ_G_DIR)/kernels_api.o: include/radar/calc_fmcw_dist.h
$(OBJ_G_DIR)/read_trace.o: include/kernels_api.h
$(OBJ_G_DIR)/read_trace.o: include/read_trace.h
$(OBJ_G_DIR)/h264/cavlc.o: include/h264/global.h
$(OBJ_G_DIR)/h264/cavlc.o: include/h264/vlc.h
$(OBJ_G_DIR)/h264/decode.o: include/h264/global.h 
$(OBJ_G_DIR)/h264/decode.o: include/h264/parset.h 
$(OBJ_G_DIR)/h264/decode.o: include/h264/decode.h 
$(OBJ_G_DIR)/h264/decode.o: include/h264/slice.h
$(OBJ_G_DIR)/h264/framealloc.o: include/h264/global.h 
$(OBJ_G_DIR)/h264/interpred.o: include/h264/global.h 
$(OBJ_G_DIR)/h264/interpred.o: include/h264/vlc.h 
$(OBJ_G_DIR)/h264/interpred.o: include/h264/mathfunc.h
$(OBJ_G_DIR)/h264/mathfunc.o: include/h264/global.h
$(OBJ_G_DIR)/h264/mathfunc.o: include/h264/mathfunc.h
$(OBJ_G_DIR)/h264/nalu.o: include/h264/global.h
$(OBJ_G_DIR)/h264/parset.o: include/h264/global.h
$(OBJ_G_DIR)/h264/parset.o: include/h264/framealloc.h
$(OBJ_G_DIR)/h264/parset.o: include/h264/vlc.h
$(OBJ_G_DIR)/h264/residual.o: include/h264/global.h 
$(OBJ_G_DIR)/h264/slice.o: include/h264/global.h
$(OBJ_G_DIR)/h264/slice.o: include/h264/intrapred.h
$(OBJ_G_DIR)/h264/slice.o: include/h264/vlc.h
$(OBJ_G_DIR)/h264/slice.o: include/h264/cavlc.h
$(OBJ_G_DIR)/h264/slice.o: include/h264/mathfunc.h
$(OBJ_G_DIR)/h264/slice.o: include/h264/residual.h
$(OBJ_G_DIR)/h264/slice.o: include/h264/interpred.h
$(OBJ_G_DIR)/h264/vlc.o: include/h264/global.h
$(OBJ_G_DIR)/h264/do_h264_decode.o: h264/global.h 
$(OBJ_G_DIR)/h264/do_h264_decode.o: include/h264/nalu.h 
$(OBJ_G_DIR)/h264/do_h264_decode.o: include/h264/decode.h
$(OBJ_G_DIR)/lv4/lv4.o: include/lv4/lv4.h
$(OBJ_G_DIR)/sdr/xmit_pipe.o: include/sdr/debug.h
$(OBJ_G_DIR)/sdr/xmit_pipe.o: include/sdr/base.h
$(OBJ_G_DIR)/sdr/xmit_pipe.o: include/sdr/xmit_pipe.h
$(OBJ_G_DIR)/sdr/xmit_pipe.o: include/sdr/fft.h
$(OBJ_G_DIR)/sdr/xmit_pipe.o: include/sdr/crc.h
$(OBJ_G_DIR)/sdr/crc.o: include/sdr/crc.h
$(OBJ_G_DIR)/sdr/recv_pipe.o: include/sdr/debug.h
$(OBJ_G_DIR)/sdr/recv_pipe.o: include/sdr/type.h
$(OBJ_G_DIR)/sdr/recv_pipe.o: include/sdr/base.h
$(OBJ_G_DIR)/sdr/recv_pipe.o: include/sdr/delay.h
$(OBJ_G_DIR)/sdr/recv_pipe.o: include/sdr/complex_ops.h
$(OBJ_G_DIR)/sdr/recv_pipe.o: include/sdr/fir.h
$(OBJ_G_DIR)/sdr/recv_pipe.o: include/sdr/sync_short.h
$(OBJ_G_DIR)/sdr/recv_pipe.o: include/sdr/sync_long.h
$(OBJ_G_DIR)/sdr/recv_pipe.o: include/sdr/gr_equalizer.h
$(OBJ_G_DIR)/sdr/recv_pipe.o: include/sdr/ofdm.h
$(OBJ_G_DIR)/sdr/recv_pipe.o: include/sdr/recv_pipe.h
$(OBJ_G_DIR)/sdr/recv_pipe.o: include/sdr/recv_pipe.h
$(OBJ_G_DIR)/sdr/complex_ops.o: include/sdr/complex_ops.h
$(OBJ_G_DIR)/sdr/complex_ops.o: include/sdr/type.h
$(OBJ_G_DIR)/sdr/complex_ops.o: include/sdr/base.h
$(OBJ_G_DIR)/sdr/delay.o: include/sdr/debug.h
$(OBJ_G_DIR)/sdr/delay.o: include/sdr/delay.h
$(OBJ_G_DIR)/sdr/delay.o: include/sdr/type.h
$(OBJ_G_DIR)/sdr/delay.o: include/sdr/base.h
$(OBJ_G_DIR)/sdr/gr_equalizer.o: include/sdr/debug.h
$(OBJ_G_DIR)/sdr/gr_equalizer.o: include/sdr/type.h
$(OBJ_G_DIR)/sdr/gr_equalizer.o: include/sdr/base.h
$(OBJ_G_DIR)/sdr/gr_equalizer.o: include/sdr/sdr_viterbi.h
$(OBJ_G_DIR)/sdr/gr_equalizer.o: include/sdr/gr_equalizer.h
$(OBJ_G_DIR)/sdr/ofdm.o: include/sdr/debug.h
$(OBJ_G_DIR)/sdr/ofdm.o: include/sdr/type.h
$(OBJ_G_DIR)/sdr/ofdm.o: include/sdr/base.h
$(OBJ_G_DIR)/sdr/ofdm.o: include/sdr/ofdm.h
$(OBJ_G_DIR)/sdr/ofdm.o: include/sdr/sdr_viterbi.h
$(OBJ_G_DIR)/sdr/sync_long.o: include/sdr/debug.h
$(OBJ_G_DIR)/sdr/sync_long.o: include/sdr/complex_ops.h
$(OBJ_G_DIR)/sdr/sync_long.o: include/sdr/type.h
$(OBJ_G_DIR)/sdr/sync_long.o: include/sdr/base.h
$(OBJ_G_DIR)/sdr/sync_long.o: include/sdr/sync_long.h
$(OBJ_G_DIR)/sdr/fir.o: include/sdr/debug.h
$(OBJ_G_DIR)/sdr/fir.o: include/sdr/type.h
$(OBJ_G_DIR)/sdr/fir.o: include/sdr/sync_short.h
$(OBJ_G_DIR)/sdr/fir.o: include/sdr/base.h
$(OBJ_G_DIR)/sdr/fir.o: include/sdr/fir.h
$(OBJ_G_DIR)/sdr/sync_short.o: include/sdr/debug.h
$(OBJ_G_DIR)/sdr/sync_short.o: include/sdr/sync_short.h
$(OBJ_G_DIR)/sdr/sync_short.o: include/sdr/type.h
$(OBJ_G_DIR)/sdr/sync_short.o: include/sdr/base.h
$(OBJ_G_DIR)/sdr/sdr_viterbi.o: include/sdr/debug.h 
$(OBJ_G_DIR)/sdr/sdr_viterbi.o: include/sdr/base.h 
$(OBJ_G_DIR)/sdr/sdr_viterbi.o: include/sdr/sdr_viterbi.h
$(OBJ_G_DIR)/sdr/descrambler_function.o: include/sdr/debug.h 
$(OBJ_G_DIR)/sdr/descrambler_function.o: include/sdr/base.h
$(OBJ_G_DIR)/sdr/simple_dft.o: include/sdr/debug.h
$(OBJ_G_DIR)/sdr/simple_dft.o: include/sdr/simple_dft.h
$(OBJ_G_DIR)/sdr/fft.o: include/sdr/fft.h
$(OBJ_G_DIR)/sdr/fft.o: include/sdr/debug.h

$(C_OBJ_G_DIR)/main.o: include/kernels_api.h
$(C_OBJ_G_DIR)/kernels_api.o: include/kernels_api.h
$(C_OBJ_G_DIR)/kernels_api.o: include/read_trace.h
$(C_OBJ_G_DIR)/kernels_api.o: include/radar/calc_fmcw_dist.h
$(C_OBJ_G_DIR)/read_trace.o: include/kernels_api.h
$(C_OBJ_G_DIR)/read_trace.o: include/read_trace.h
$(C_OBJ_G_DIR)/h264/cavlc.o: include/h264/global.h
$(C_OBJ_G_DIR)/h264/cavlc.o: include/h264/vlc.h
$(C_OBJ_G_DIR)/h264/decode.o: include/h264/global.h 
$(C_OBJ_G_DIR)/h264/decode.o: include/h264/parset.h 
$(C_OBJ_G_DIR)/h264/decode.o: include/h264/decode.h 
$(C_OBJ_G_DIR)/h264/decode.o: include/h264/slice.h
$(C_OBJ_G_DIR)/h264/framealloc.o: include/h264/global.h 
$(C_OBJ_G_DIR)/h264/interpred.o: include/h264/global.h 
$(C_OBJ_G_DIR)/h264/interpred.o: include/h264/vlc.h 
$(C_OBJ_G_DIR)/h264/interpred.o: include/h264/mathfunc.h
$(C_OBJ_G_DIR)/h264/mathfunc.o: include/h264/global.h
$(C_OBJ_G_DIR)/h264/mathfunc.o: include/h264/mathfunc.h
$(C_OBJ_G_DIR)/h264/nalu.o: include/h264/global.h
$(C_OBJ_G_DIR)/h264/parset.o: include/h264/global.h
$(C_OBJ_G_DIR)/h264/parset.o: include/h264/framealloc.h
$(C_OBJ_G_DIR)/h264/parset.o: include/h264/vlc.h
$(C_OBJ_G_DIR)/h264/residual.o: include/h264/global.h 
$(C_OBJ_G_DIR)/h264/slice.o: include/h264/global.h
$(C_OBJ_G_DIR)/h264/slice.o: include/h264/intrapred.h
$(C_OBJ_G_DIR)/h264/slice.o: include/h264/vlc.h
$(C_OBJ_G_DIR)/h264/slice.o: include/h264/cavlc.h
$(C_OBJ_G_DIR)/h264/slice.o: include/h264/mathfunc.h
$(C_OBJ_G_DIR)/h264/slice.o: include/h264/residual.h
$(C_OBJ_G_DIR)/h264/slice.o: include/h264/interpred.h
$(C_OBJ_G_DIR)/h264/vlc.o: include/h264/global.h
$(C_OBJ_G_DIR)/h264/do_h264_decode.o: h264/global.h 
$(C_OBJ_G_DIR)/h264/do_h264_decode.o: include/h264/nalu.h 
$(C_OBJ_G_DIR)/h264/do_h264_decode.o: include/h264/decode.h
$(C_OBJ_G_DIR)/lv4/lv4.o: include/lv4/lv4.h
$(C_OBJ_G_DIR)/sdr/xmit_pipe.o: include/sdr/debug.h
$(C_OBJ_G_DIR)/sdr/xmit_pipe.o: include/sdr/base.h
$(C_OBJ_G_DIR)/sdr/xmit_pipe.o: include/sdr/xmit_pipe.h
$(C_OBJ_G_DIR)/sdr/xmit_pipe.o: include/sdr/fft.h
$(C_OBJ_G_DIR)/sdr/xmit_pipe.o: include/sdr/crc.h
$(C_OBJ_G_DIR)/sdr/crc.o: include/sdr/crc.h
$(C_OBJ_G_DIR)/sdr/recv_pipe.o: include/sdr/debug.h
$(C_OBJ_G_DIR)/sdr/recv_pipe.o: include/sdr/type.h
$(C_OBJ_G_DIR)/sdr/recv_pipe.o: include/sdr/base.h
$(C_OBJ_G_DIR)/sdr/recv_pipe.o: include/sdr/delay.h
$(C_OBJ_G_DIR)/sdr/recv_pipe.o: include/sdr/complex_ops.h
$(C_OBJ_G_DIR)/sdr/recv_pipe.o: include/sdr/fir.h
$(C_OBJ_G_DIR)/sdr/recv_pipe.o: include/sdr/sync_short.h
$(C_OBJ_G_DIR)/sdr/recv_pipe.o: include/sdr/sync_long.h
$(C_OBJ_G_DIR)/sdr/recv_pipe.o: include/sdr/gr_equalizer.h
$(C_OBJ_G_DIR)/sdr/recv_pipe.o: include/sdr/ofdm.h
$(C_OBJ_G_DIR)/sdr/recv_pipe.o: include/sdr/recv_pipe.h
$(C_OBJ_G_DIR)/sdr/recv_pipe.o: include/sdr/recv_pipe.h
$(C_OBJ_G_DIR)/sdr/complex_ops.o: include/sdr/complex_ops.h
$(C_OBJ_G_DIR)/sdr/complex_ops.o: include/sdr/type.h
$(C_OBJ_G_DIR)/sdr/complex_ops.o: include/sdr/base.h
$(C_OBJ_G_DIR)/sdr/delay.o: include/sdr/debug.h
$(C_OBJ_G_DIR)/sdr/delay.o: include/sdr/delay.h
$(C_OBJ_G_DIR)/sdr/delay.o: include/sdr/type.h
$(C_OBJ_G_DIR)/sdr/delay.o: include/sdr/base.h
$(C_OBJ_G_DIR)/sdr/gr_equalizer.o: include/sdr/debug.h
$(C_OBJ_G_DIR)/sdr/gr_equalizer.o: include/sdr/type.h
$(C_OBJ_G_DIR)/sdr/gr_equalizer.o: include/sdr/base.h
$(C_OBJ_G_DIR)/sdr/gr_equalizer.o: include/sdr/sdr_viterbi.h
$(C_OBJ_G_DIR)/sdr/gr_equalizer.o: include/sdr/gr_equalizer.h
$(C_OBJ_G_DIR)/sdr/ofdm.o: include/sdr/debug.h
$(C_OBJ_G_DIR)/sdr/ofdm.o: include/sdr/type.h
$(C_OBJ_G_DIR)/sdr/ofdm.o: include/sdr/base.h
$(C_OBJ_G_DIR)/sdr/ofdm.o: include/sdr/ofdm.h
$(C_OBJ_G_DIR)/sdr/ofdm.o: include/sdr/sdr_viterbi.h
$(C_OBJ_G_DIR)/sdr/sync_long.o: include/sdr/debug.h
$(C_OBJ_G_DIR)/sdr/sync_long.o: include/sdr/complex_ops.h
$(C_OBJ_G_DIR)/sdr/sync_long.o: include/sdr/type.h
$(C_OBJ_G_DIR)/sdr/sync_long.o: include/sdr/base.h
$(C_OBJ_G_DIR)/sdr/sync_long.o: include/sdr/sync_long.h
$(C_OBJ_G_DIR)/sdr/fir.o: include/sdr/debug.h
$(C_OBJ_G_DIR)/sdr/fir.o: include/sdr/type.h
$(C_OBJ_G_DIR)/sdr/fir.o: include/sdr/sync_short.h
$(C_OBJ_G_DIR)/sdr/fir.o: include/sdr/base.h
$(C_OBJ_G_DIR)/sdr/fir.o: include/sdr/fir.h
$(C_OBJ_G_DIR)/sdr/sync_short.o: include/sdr/debug.h
$(C_OBJ_G_DIR)/sdr/sync_short.o: include/sdr/sync_short.h
$(C_OBJ_G_DIR)/sdr/sync_short.o: include/sdr/type.h
$(C_OBJ_G_DIR)/sdr/sync_short.o: include/sdr/base.h
$(C_OBJ_G_DIR)/sdr/sdr_viterbi.o: include/sdr/debug.h 
$(C_OBJ_G_DIR)/sdr/sdr_viterbi.o: include/sdr/base.h 
$(C_OBJ_G_DIR)/sdr/sdr_viterbi.o: include/sdr/sdr_viterbi.h
$(C_OBJ_G_DIR)/sdr/descrambler_function.o: include/sdr/debug.h 
$(C_OBJ_G_DIR)/sdr/descrambler_function.o: include/sdr/base.h
$(C_OBJ_G_DIR)/sdr/simple_dft.o: include/sdr/debug.h
$(C_OBJ_G_DIR)/sdr/simple_dft.o: include/sdr/simple_dft.h
$(C_OBJ_G_DIR)/sdr/fft.o: include/sdr/fft.h
$(C_OBJ_G_DIR)/sdr/fft.o: include/sdr/debug.h

