# Common targets, etc. for all makefiles

OBJDIR      = obj
IT_OBJDIR   = obj_it
C_OBJDIR    = obj_c
ITC_OBJDIR  = obj_itc
FC_OBJDIR   = obj_fc
ITFC_OBJDIR = obj_itfc

OBJ_V_DIR     = obj_v
C_OBJ_V_DIR   = obj_cv
FC_OBJ_V_DIR  = obj_fcv

OBJ_G_DIR    = obj_gp
C_OBJ_G_DIR  = obj_cgp



# The full mini-era target, etc.
TARGET = main
SRC    = src/kernels_api.c \
         src/main.c \
         src/radar/calculate_dist_from_fmcw.c \
         src/radar/fft.c \
         src/radar/octave.c \
         src/radar/timer.c \
	 src/viterbi/descrambler_function.c \
         src/viterbi/viterbi_flat.c \
         src/viterbi/viterbi_parms.c \
	 src/h264/cavlc.c \
	 src/h264/decode.c \
	 src/h264/framealloc.c \
	 src/h264/interpred.c \
	 src/h264/intrapred.c \
	 src/h264/mathfunc.c \
	 src/h264/nalu.c \
	 src/h264/parset.c \
	 src/h264/residual.c \
	 src/h264/slice.c \
	 src/h264/vlc.c \
	 src/h264/do_h264_decode.c \
	 src/read_trace.c


OBJ     = $(SRC:%.c=$(OBJDIR)/%.o)
OBJ_V   = $(SRC:%.c=$(OBJ_V_DIR)/%.o)
OBJ_G   = $(SRC:%.c=$(OBJ_G_DIR)/%.o)
IT_OBJ  = $(SRC:%.c=$(IT_OBJDIR)/%.o)
FOBJ    = $(SRC:%.c=$(OBJDIR)/%.o)
FOBJ_V  = $(SRC:%.c=$(OBJ_V_DIR)/%.o)
IT_FOBJ = $(SRC:%.c=$(IT_OBJDIR)/%.o)

#$(info $$SRC is [${SRC}])
#$(info $$SRC is [${SRC}])
#$(info $$IT_OBJDIR is [${IT_OBJDIR}])
#$(info $$IT_OBJ is [${IT_OBJ}])


# The C-code only target (it bypasses KERAS Python code)
C_TARGET = cmain
C_OBJ    = $(SRC:%.c=$(C_OBJDIR)/%.o)
C_OBJ_V  = $(SRC:%.c=$(C_OBJ_V_DIR)/%.o)
C_OBJ_G  = $(SRC:%.c=$(C_OBJ_G_DIR)/%.o)
ITC_OBJ  = $(SRC:%.c=$(ITC_OBJDIR)/%.o)

#TC_TARGET = t-cmain
TC_OBJ    = $(SRC:%.c=$(C_OBJDIR)/%.o)
TC_OBJ_V  = $(SRC:%.c=$(C_OBJ_V_DIR)/%.o)
TC_OBJ_G  = $(SRC!:%.c=$(C_OBJ_G_DIR)/%.o)


$(TARGET): $(OBJDIR)  $(OBJ) 
	$(CC) $(OBJ) $(CFLAGS) $(INCLUDES) $(PYTHONINCLUDES) -o $@.exe $(LFLAGS) $(LIBS) $(PYTHONLIBS)

it-$(TARGET): $(IT_OBJDIR)  $(IT_OBJ) 
	$(CC) $(IT_OBJ) $(CFLAGS) $(INCLUDES) $(PYTHONINCLUDES) -o $@.exe $(LFLAGS) $(LIBS) $(PYTHONLIBS)

f$(TARGET): $(OBJDIR)  $(OBJ) 
	$(CC) $(OBJ) $(CFLAGS) $(INCLUDES) $(PYTHONINCLUDES) -o $@.exe $(LFLAGS) $(LIBS) $(PYTHONLIBS)

it-f$(TARGET): $(OBJDIR)  $(IT_OBJ) 
	$(CC) $(IT_OBJ) $(CFLAGS) $(INCLUDES) $(PYTHONINCLUDES) -o $@.exe $(LFLAGS) $(LIBS) $(PYTHONLIBS)

$(C_TARGET): $(C_OBJDIR) $(C_OBJ) 
	$(CC) $(C_OBJ) $(CFLAGS) $(INCLUDES) $(PYTHONINCLUDES) -o $@.exe $(LFLAGS) $(LIBS) $(CPYTHONLIBS)

it-$(C_TARGET): $(ITC_OBJDIR) $(ITC_OBJ) 
	$(CC) $(ITC_OBJ) $(CFLAGS) $(INCLUDES) $(PYTHONINCLUDES) -o $@.exe $(LFLAGS) $(LIBS) $(CPYTHONLIBS)

v$(TARGET): $(OBJ_V_DIR) $(OBJ_V) 
	$(CC) $(OBJ_V) $(CFLAGS) $(INCLUDES) $(PYTHONINCLUDES) -o $@.exe $(LFLAGS) $(LIBS) $(PYTHONLIBS)

v$(C_TARGET): $(C_OBJ_V_DIR) $(C_OBJ_V) 
	$(CC) $(C_OBJ_V) $(CFLAGS) $(INCLUDES) $(PYTHONINCLUDES) -o $@.exe $(LFLAGS) $(LIBS) $(CPYTHONLIBS)



gp_$(TARGET): $(OBJ_G_DIR) $(OBJ_G) 
	$(CC) $(OBJ_G) $(CFLAGS) $(INCLUDES) $(PYTHONINCLUDES) -pg -o $@.exe $(LFLAGS) $(LIBS) $(PYTHONLIBS)

gp_$(C_TARGET): $(C_OBJ_G_DIR) $(C_OBJ_G) 
	$(CC) $(C_OBJ_G) $(CFLAGS) $(INCLUDES) $(PYTHONINCLUDES) -pg -o $@.exe $(LFLAGS) $(LIBS) $(CPYTHONLIBS)


$(S_TARGET): $(S_OBJDIR)  $(S_OBJ) 
	$(CC) $(S_OBJ) $(CFLAGS) $(INCLUDES) $(PYTHONINCLUDES) -o $@.exe $(LFLAGS) $(LIBS) $(PYTHONLIBS)

it-$(S_TARGET): $(ITS_OBJDIR)  $(ITS_OBJ) 
	$(CC) $(ITS_OBJ) $(CFLAGS) $(INCLUDES) $(PYTHONINCLUDES) -o $@.exe $(LFLAGS) $(LIBS) $(PYTHONLIBS)




ctrace: cobjdirs $(C_TARGET) it-$(C_TARGET) v$(C_TARGET) gp_$(C_TARGET) 

trace: objdirs $(TARGET) it-$(TARGET) v$(TARGET) gp_$(TARGET)

all: objdirs trace cver

cver: cobjdirs ctrace 

objdirs: $(OBJDIR) $(IT_OBJDIR) $(OBJ_V_DIR) $(OBJ_G_DIR) $(S_OBJDIR) $(ITS_OBJDIR) $(S_OBJ_V_DIR) $(S_OBJ_G_DIR)

cobjdirs: $(C_OBJDIR) $(FC_OBJDIR) $(ITC_OBJDIR) $(ITFC_OBJDIR) $(C_OBJ_V_DIR) $(FC_OBJ_V_DIR) $(C_OBJ_G_DIR)



util_prog:
	cd utils; make -f $(MFILE) all

test: 
	cd utils; make -f $(MFILE) test

vtest: 
	cd utils; make -f $(MFILE) vtest

tracegen: 
	cd utils; make -f $(MFILE) tracegen



$(OBJDIR):
	mkdir $@
	mkdir -p $@/src/viterbi
	mkdir -p $@/src/radar
	mkdir -p $@/src/h264

$(T_OBJDIR):
	mkdir $@
	mkdir -p $@/src/viterbi
	mkdir -p $@/src/radar
	mkdir -p $@/src/h264

$(IT_OBJDIR):
	mkdir $@
	mkdir -p $@/src/viterbi
	mkdir -p $@/src/radar
	mkdir -p $@/src/h264

$(C_OBJDIR):
	mkdir $@
	mkdir -p $@/src/viterbi
	mkdir -p $@/src/radar
	mkdir -p $@/src/h264

$(TC_OBJDIR):
	mkdir $@
	mkdir -p $@/src/viterbi
	mkdir -p $@/src/radar
	mkdir -p $@/src/h264

$(ITC_OBJDIR):
	mkdir $@
	mkdir -p $@/src/viterbi
	mkdir -p $@/src/radar
	mkdir -p $@/src/h264

$(FC_OBJDIR):
	mkdir $@
	mkdir -p $@/src/viterbi
	mkdir -p $@/src/radar
	mkdir -p $@/src/h264

$(TFC_OBJDIR):
	mkdir $@
	mkdir -p $@/src/viterbi
	mkdir -p $@/src/radar
	mkdir -p $@/src/h264

$(ITFC_OBJDIR):
	mkdir $@
	mkdir -p $@/src/viterbi
	mkdir -p $@/src/radar
	mkdir -p $@/src/h264

$(OBJ_V_DIR):
	mkdir $@
	mkdir -p $@/src/viterbi
	mkdir -p $@/src/radar
	mkdir -p $@/src/h264

$(T_OBJ_V_DIR):
	mkdir $@
	mkdir -p $@/src/viterbi
	mkdir -p $@/src/radar
	mkdir -p $@/src/h264

$(C_OBJ_V_DIR):
	mkdir $@
	mkdir -p $@/src/viterbi
	mkdir -p $@/src/radar
	mkdir -p $@/src/h264

$(TC_OBJ_V_DIR):
	mkdir $@
	mkdir -p $@/src/viterbi
	mkdir -p $@/src/radar
	mkdir -p $@/src/h264

$(FC_OBJ_V_DIR):
	mkdir $@
	mkdir -p $@/src/viterbi
	mkdir -p $@/src/radar
	mkdir -p $@/src/h264

$(TFC_OBJ_V_DIR):
	mkdir $@
	mkdir -p $@/src/viterbi
	mkdir -p $@/src/radar
	mkdir -p $@/src/h264

$(OBJ_G_DIR):
	mkdir $@
	mkdir -p $@/src/viterbi
	mkdir -p $@/src/radar
	mkdir -p $@/src/h264

$(T_OBJ_G_DIR):
	mkdir $@
	mkdir -p $@/src/viterbi
	mkdir -p $@/src/radar
	mkdir -p $@/src/h264

$(C_OBJ_G_DIR):
	mkdir $@
	mkdir -p $@/src/viterbi
	mkdir -p $@/src/radar
	mkdir -p $@/src/h264

$(TC_OBJ_G_DIR):
	mkdir $@
	mkdir -p $@/src/viterbi
	mkdir -p $@/src/radar
	mkdir -p $@/src/h264




$(OBJDIR)/%.o: %.c
	$(CC) $(CFLAGS) $(PYTHONINCLUDES) -o $@ $(PYTHONLIBS) -c $<

$(T_OBJDIR)/%.o: %.c
	$(CC) $(CFLAGS) $(PYTHONINCLUDES) -o $@ $(PYTHONLIBS) -c $<

$(IT_OBJDIR)/%.o: %.c
	$(CC) $(CFLAGS) $(PYTHONINCLUDES) -DINT_TIME -o $@ $(PYTHONLIBS) -c $<

$(C_OBJDIR)/%.o: %.c
	$(CC) $(CFLAGS) $(PYTHONINCLUDES) -DBYPASS_KERAS_CV_CODE -o $@ $(PYTHONLIBS) -c $<

$(TC_OBJDIR)/%.o: %.c
	$(CC) $(CFLAGS) $(PYTHONINCLUDES) -DINT_TIME -DBYPASS_KERAS_CV_CODE -o $@ $(PYTHONLIBS) -c $<

$(ITC_OBJDIR)/%.o: %.c
	$(CC) $(CFLAGS) $(PYTHONINCLUDES) -DINT_TIME -DBYPASS_KERAS_CV_CODE -o $@ $(PYTHONLIBS) -c $<

$(FC_OBJDIR)/%.o: %.c
	$(CC) $(CFLAGS) $(PYTHONINCLUDES) -DBYPASS_KERAS_CV_CODE -o $@ $(PYTHONLIBS) -c $<

$(TFC_OBJDIR)/%.o: %.c
	$(CC) $(CFLAGS) $(PYTHONINCLUDES) -DINT_TIME -DBYPASS_KERAS_CV_CODE -o $@ $(PYTHONLIBS) -c $<

$(ITFC_OBJDIR)/%.o: %.c
	$(CC) $(CFLAGS) $(PYTHONINCLUDES) -DINT_TIME -DBYPASS_KERAS_CV_CODE -o $@ $(PYTHONLIBS) -c $<

$(OBJ_V_DIR)/%.o: %.c
	$(CC) $(CFLAGS) $(PYTHONINCLUDES) -DVERBOSE -o $@ $(PYTHONLIBS) -c $<

$(C_OBJ_V_DIR)/%.o: %.c
	$(CC) $(CFLAGS) $(PYTHONINCLUDES) -DVERBOSE -DBYPASS_KERAS_CV_CODE -o $@ $(PYTHONLIBS) -c $<

$(FC_OBJ_V_DIR)/%.o: %.c
	$(CC) $(CFLAGS) $(PYTHONINCLUDES) -DVERBOSE -DBYPASS_KERAS_CV_CODE -o $@ $(PYTHONLIBS) -c $<

$(OBJ_G_DIR)/%.o: %.c
	$(CC) $(CFLAGS) $(PYTHONINCLUDES) -g -pg -o $@ $(PYTHONLIBS) -c $<

$(C_OBJ_G_DIR)/%.o: %.c
	$(CC) $(CFLAGS) $(PYTHONINCLUDES) -DBYPASS_KERAS_CV_CODE -g -pg -o $@ $(PYTHONLIBS) -c $<



$(S_OBJDIR)/%.o: %.c
	$(CC) $(CFLAGS) $(PYTHONINCLUDES) -DUSE_SIM_ENVIRON -o $@ $(PYTHONLIBS) -c $<

$(TS_OBJDIR)/%.o: %.c
	$(CC) $(CFLAGS) $(PYTHONINCLUDES) -DINT_TIME -DUSE_SIM_ENVIRON -o $@ $(PYTHONLIBS) -c $<

$(ITS_OBJDIR)/%.o: %.c
	$(CC) $(CFLAGS) $(PYTHONINCLUDES) -DINT_TIME -DUSE_SIM_ENVIRON -o $@ $(PYTHONLIBS) -c $<

$(S_OBJ_V_DIR)/%.o: %.c
	$(CC) $(CFLAGS) $(PYTHONINCLUDES) -DUSE_SIM_ENVIRON -DVERBOSE -o $@ $(PYTHONLIBS) -c $<




clean:
	$(RM) $(TARGET).exe $(OBJ)
	$(RM) it-$(TARGET).exe $(IT_OBJ)
	$(RM) $(C_TARGET).exe $(C_OBJ)
	$(RM) it-$(C_TARGET).exe $(ITC_OBJ)
	$(RM) v$(TARGET).exe $(OBJ_V)
	$(RM) v$(C_TARGET).exe $(C_OBJ_V)
	$(RM) gp_$(TARGET).exe $(OBJ_G)
	$(RM) gp_$(C_TARGET).exe $(C_OBJ_G)
	$(RM) $(S_TARGET).exe $(S_OBJ)

clobber: clean
	$(RM) -rf $(OBJDIR) $(IT_OBJDIR)
	$(RM) -rf $(C_OBJDIR) $(ITC_OBJDIR)
	$(RM) -rf $(FC_OBJDIR) $(ITFC_OBJDIR)
	$(RM) -rf $(OBJ_V_DIR) $(C_OBJ_V_DIR) $(FC_OBJ_V_DIR)
	$(RM) -rf $(OBJ_G_DIR) $(C_OBJ_G_DIR)

allclean: clobber
	cd utils; make -f $(MFILE) allclean
	cd radar; make -f $(MFILE) clean
	cd viterbi; make -f $(MFILE) clean


$(OBJDIR)/kernels_api.o: include/kernels_api.h
$(OBJDIR)/kernels_api.o: include/read_trace.h
$(OBJDIR)/kernels_api.o: include/viterbi/utils.h
$(OBJDIR)/kernels_api.o: include/viterbi/viterbi_decoder_generic.h
$(OBJDIR)/kernels_api.o: include/radar/calc_fmcw_dist.h
$(OBJDIR)/read_trace.o: include/kernels_api.h
$(OBJDIR)/read_trace.o: include/read_trace.h
$(OBJDIR)/h264/cavlc.o: include/h264/global.h
$(OBJDIR)/h264/cavlc.o: include/h264/vlc.h
$(OBJDIR)/h264/decode.o: include/h264/global.h 
$(OBJDIR)/h264/decode.o: include/h264/parset.h 
$(OBJDIR)/h264/decode.o: include/h264/decode.h 
$(OBJDIR)/h264/decode.o: include/h264/slice.h
$(OBJDIR)/h264/framealloc.o: include/h264/global.h 
$(OBJDIR)/h264/interpred.o: include/h264/global.h 
$(OBJDIR)/h264/interpred.o: include/h264/vlc.h 
$(OBJDIR)/h264/interpred.o: include/h264/mathfunc.h
$(OBJDIR)/h264/mathfunc.o: include/h264/global.h
$(OBJDIR)/h264/mathfunc.o: include/h264/mathfunc.h
$(OBJDIR)/h264/nalu.o: include/h264/global.h
$(OBJDIR)/h264/parset.o: include/h264/global.h
$(OBJDIR)/h264/parset.o: include/h264/framealloc.h
$(OBJDIR)/h264/parset.o: include/h264/vlc.h
$(OBJDIR)/h264/residual.o: include/h264/global.h 
$(OBJDIR)/h264/slice.o: include/h264/global.h
$(OBJDIR)/h264/slice.o: include/h264/intrapred.h
$(OBJDIR)/h264/slice.o: include/h264/vlc.h
$(OBJDIR)/h264/slice.o: include/h264/cavlc.h
$(OBJDIR)/h264/slice.o: include/h264/mathfunc.h
$(OBJDIR)/h264/slice.o: include/h264/residual.h
$(OBJDIR)/h264/slice.o: include/h264/interpred.h
$(OBJDIR)/h264/vlc.o: include/h264/global.h
$(OBJDIR)/h264/do_h264_decode.o: h264/global.h 
$(OBJDIR)/h264/do_h264_decode.o: include/h264/nalu.h 
$(OBJDIR)/h264/do_h264_decode.o: include/h264/decode.h

$(C_OBJDIR)/kernels_api.o: include/kernels_api.h
$(C_OBJDIR)/kernels_api.o: include/read_trace.h
$(C_OBJDIR)/kernels_api.o: include/viterbi/utils.h
$(C_OBJDIR)/kernels_api.o: include/viterbi/viterbi_decoder_generic.h
$(C_OBJDIR)/kernels_api.o: include/radar/calc_fmcw_dist.h
$(C_OBJDIR)/read_trace.o: include/kernels_api.h
$(C_OBJDIR)/read_trace.o: include/read_trace.h
$(C_OBJDIR)/h264/cavlc.o: include/h264/global.h
$(C_OBJDIR)/h264/cavlc.o: include/h264/vlc.h
$(C_OBJDIR)/h264/decode.o: include/h264/global.h 
$(C_OBJDIR)/h264/decode.o: include/h264/parset.h 
$(C_OBJDIR)/h264/decode.o: include/h264/decode.h 
$(C_OBJDIR)/h264/decode.o: include/h264/slice.h
$(C_OBJDIR)/h264/framealloc.o: include/h264/global.h 
$(C_OBJDIR)/h264/interpred.o: include/h264/global.h 
$(C_OBJDIR)/h264/interpred.o: include/h264/vlc.h 
$(C_OBJDIR)/h264/interpred.o: include/h264/mathfunc.h
$(C_OBJDIR)/h264/mathfunc.o: include/h264/global.h
$(C_OBJDIR)/h264/mathfunc.o: include/h264/mathfunc.h
$(C_OBJDIR)/h264/nalu.o: include/h264/global.h
$(C_OBJDIR)/h264/parset.o: include/h264/global.h
$(C_OBJDIR)/h264/parset.o: include/h264/framealloc.h
$(C_OBJDIR)/h264/parset.o: include/h264/vlc.h
$(C_OBJDIR)/h264/residual.o: include/h264/global.h 
$(C_OBJDIR)/h264/slice.o: include/h264/global.h
$(C_OBJDIR)/h264/slice.o: include/h264/intrapred.h
$(C_OBJDIR)/h264/slice.o: include/h264/vlc.h
$(C_OBJDIR)/h264/slice.o: include/h264/cavlc.h
$(C_OBJDIR)/h264/slice.o: include/h264/mathfunc.h
$(C_OBJDIR)/h264/slice.o: include/h264/residual.h
$(C_OBJDIR)/h264/slice.o: include/h264/interpred.h
$(C_OBJDIR)/h264/vlc.o: include/h264/global.h
$(C_OBJDIR)/h264/do_h264_decode.o: h264/global.h 
$(C_OBJDIR)/h264/do_h264_decode.o: include/h264/nalu.h 
$(C_OBJDIR)/h264/do_h264_decode.o: include/h264/decode.h

$(OBJ_V_DIR)/kernels_api.o: include/kernels_api.h
$(OBJ_V_DIR)/kernels_api.o: include/read_trace.h
$(OBJ_V_DIR)/kernels_api.o: include/viterbi/utils.h
$(OBJ_V_DIR)/kernels_api.o: include/viterbi/viterbi_decoder_generic.h
$(OBJ_V_DIR)/kernels_api.o: include/radar/calc_fmcw_dist.h
$(OBJ_V_DIR)/read_trace.o: include/kernels_api.h
$(OBJ_V_DIR)/read_trace.o: include/read_trace.h
$(OBJ_V_DIR)/h264/cavlc.o: include/h264/global.h
$(OBJ_V_DIR)/h264/cavlc.o: include/h264/vlc.h
$(OBJ_V_DIR)/h264/decode.o: include/h264/global.h 
$(OBJ_V_DIR)/h264/decode.o: include/h264/parset.h 
$(OBJ_V_DIR)/h264/decode.o: include/h264/decode.h 
$(OBJ_V_DIR)/h264/decode.o: include/h264/slice.h
$(OBJ_V_DIR)/h264/framealloc.o: include/h264/global.h 
$(OBJ_V_DIR)/h264/interpred.o: include/h264/global.h 
$(OBJ_V_DIR)/h264/interpred.o: include/h264/vlc.h 
$(OBJ_V_DIR)/h264/interpred.o: include/h264/mathfunc.h
$(OBJ_V_DIR)/h264/mathfunc.o: include/h264/global.h
$(OBJ_V_DIR)/h264/mathfunc.o: include/h264/mathfunc.h
$(OBJ_V_DIR)/h264/nalu.o: include/h264/global.h
$(OBJ_V_DIR)/h264/parset.o: include/h264/global.h
$(OBJ_V_DIR)/h264/parset.o: include/h264/framealloc.h
$(OBJ_V_DIR)/h264/parset.o: include/h264/vlc.h
$(OBJ_V_DIR)/h264/residual.o: include/h264/global.h 
$(OBJ_V_DIR)/h264/slice.o: include/h264/global.h
$(OBJ_V_DIR)/h264/slice.o: include/h264/intrapred.h
$(OBJ_V_DIR)/h264/slice.o: include/h264/vlc.h
$(OBJ_V_DIR)/h264/slice.o: include/h264/cavlc.h
$(OBJ_V_DIR)/h264/slice.o: include/h264/mathfunc.h
$(OBJ_V_DIR)/h264/slice.o: include/h264/residual.h
$(OBJ_V_DIR)/h264/slice.o: include/h264/interpred.h
$(OBJ_V_DIR)/h264/vlc.o: include/h264/global.h
$(OBJ_V_DIR)/h264/do_h264_decode.o: h264/global.h 
$(OBJ_V_DIR)/h264/do_h264_decode.o: include/h264/nalu.h 
$(OBJ_V_DIR)/h264/do_h264_decode.o: include/h264/decode.h

$(C_OBJ_V_DIR)/kernels_api.o: include/kernels_api.h
$(C_OBJ_V_DIR)/kernels_api.o: include/read_trace.h
$(C_OBJ_V_DIR)/kernels_api.o: include/viterbi/utils.h
$(C_OBJ_V_DIR)/kernels_api.o: include/viterbi/viterbi_decoder_generic.h
$(C_OBJ_V_DIR)/kernels_api.o: include/radar/calc_fmcw_dist.h
$(C_OBJ_V_DIR)/read_trace.o: include/kernels_api.h
$(C_OBJ_V_DIR)/read_trace.o: include/read_trace.h
$(C_OBJ_V_DIR)/h264/cavlc.o: include/h264/global.h
$(C_OBJ_V_DIR)/h264/cavlc.o: include/h264/vlc.h
$(C_OBJ_V_DIR)/h264/decode.o: include/h264/global.h 
$(C_OBJ_V_DIR)/h264/decode.o: include/h264/parset.h 
$(C_OBJ_V_DIR)/h264/decode.o: include/h264/decode.h 
$(C_OBJ_V_DIR)/h264/decode.o: include/h264/slice.h
$(C_OBJ_V_DIR)/h264/framealloc.o: include/h264/global.h 
$(C_OBJ_V_DIR)/h264/interpred.o: include/h264/global.h 
$(C_OBJ_V_DIR)/h264/interpred.o: include/h264/vlc.h 
$(C_OBJ_V_DIR)/h264/interpred.o: include/h264/mathfunc.h
$(C_OBJ_V_DIR)/h264/mathfunc.o: include/h264/global.h
$(C_OBJ_V_DIR)/h264/mathfunc.o: include/h264/mathfunc.h
$(C_OBJ_V_DIR)/h264/nalu.o: include/h264/global.h
$(C_OBJ_V_DIR)/h264/parset.o: include/h264/global.h
$(C_OBJ_V_DIR)/h264/parset.o: include/h264/framealloc.h
$(C_OBJ_V_DIR)/h264/parset.o: include/h264/vlc.h
$(C_OBJ_V_DIR)/h264/residual.o: include/h264/global.h 
$(C_OBJ_V_DIR)/h264/slice.o: include/h264/global.h
$(C_OBJ_V_DIR)/h264/slice.o: include/h264/intrapred.h
$(C_OBJ_V_DIR)/h264/slice.o: include/h264/vlc.h
$(C_OBJ_V_DIR)/h264/slice.o: include/h264/cavlc.h
$(C_OBJ_V_DIR)/h264/slice.o: include/h264/mathfunc.h
$(C_OBJ_V_DIR)/h264/slice.o: include/h264/residual.h
$(C_OBJ_V_DIR)/h264/slice.o: include/h264/interpred.h
$(C_OBJ_V_DIR)/h264/vlc.o: include/h264/global.h
$(C_OBJ_V_DIR)/h264/do_h264_decode.o: h264/global.h 
$(C_OBJ_V_DIR)/h264/do_h264_decode.o: include/h264/nalu.h 
$(C_OBJ_V_DIR)/h264/do_h264_decode.o: include/h264/decode.h


$(OBJ_G_DIR)/kernels_api.o: include/kernels_api.h
$(OBJ_G_DIR)/kernels_api.o: include/read_trace.h
$(OBJ_G_DIR)/kernels_api.o: include/viterbi/utils.h
$(OBJ_G_DIR)/kernels_api.o: include/viterbi/viterbi_decoder_generic.h
$(OBJ_G_DIR)/kernels_api.o: include/radar/calc_fmcw_dist.h
$(OBJ_G_DIR)/read_trace.o: include/kernels_api.h
$(OBJ_G_DIR)/read_trace.o: include/read_trace.h
$(OBJ_G_DIR)/h264/cavlc.o: include/h264/global.h
$(OBJ_G_DIR)/h264/cavlc.o: include/h264/vlc.h
$(OBJ_G_DIR)/h264/decode.o: include/h264/global.h 
$(OBJ_G_DIR)/h264/decode.o: include/h264/parset.h 
$(OBJ_G_DIR)/h264/decode.o: include/h264/decode.h 
$(OBJ_G_DIR)/h264/decode.o: include/h264/slice.h
$(OBJ_G_DIR)/h264/framealloc.o: include/h264/global.h 
$(OBJ_G_DIR)/h264/interpred.o: include/h264/global.h 
$(OBJ_G_DIR)/h264/interpred.o: include/h264/vlc.h 
$(OBJ_G_DIR)/h264/interpred.o: include/h264/mathfunc.h
$(OBJ_G_DIR)/h264/mathfunc.o: include/h264/global.h
$(OBJ_G_DIR)/h264/mathfunc.o: include/h264/mathfunc.h
$(OBJ_G_DIR)/h264/nalu.o: include/h264/global.h
$(OBJ_G_DIR)/h264/parset.o: include/h264/global.h
$(OBJ_G_DIR)/h264/parset.o: include/h264/framealloc.h
$(OBJ_G_DIR)/h264/parset.o: include/h264/vlc.h
$(OBJ_G_DIR)/h264/residual.o: include/h264/global.h 
$(OBJ_G_DIR)/h264/slice.o: include/h264/global.h
$(OBJ_G_DIR)/h264/slice.o: include/h264/intrapred.h
$(OBJ_G_DIR)/h264/slice.o: include/h264/vlc.h
$(OBJ_G_DIR)/h264/slice.o: include/h264/cavlc.h
$(OBJ_G_DIR)/h264/slice.o: include/h264/mathfunc.h
$(OBJ_G_DIR)/h264/slice.o: include/h264/residual.h
$(OBJ_G_DIR)/h264/slice.o: include/h264/interpred.h
$(OBJ_G_DIR)/h264/vlc.o: include/h264/global.h
$(OBJ_G_DIR)/h264/do_h264_decode.o: h264/global.h 
$(OBJ_G_DIR)/h264/do_h264_decode.o: include/h264/nalu.h 
$(OBJ_G_DIR)/h264/do_h264_decode.o: include/h264/decode.h

$(C_OBJ_G_DIR)/kernels_api.o: include/kernels_api.h
$(C_OBJ_G_DIR)/kernels_api.o: include/read_trace.h
$(C_OBJ_G_DIR)/kernels_api.o: include/viterbi/utils.h
$(C_OBJ_G_DIR)/kernels_api.o: include/viterbi/viterbi_decoder_generic.h
$(C_OBJ_G_DIR)/kernels_api.o: include/radar/calc_fmcw_dist.h
$(C_OBJ_G_DIR)/read_trace.o: include/kernels_api.h
$(C_OBJ_G_DIR)/read_trace.o: include/read_trace.h
$(C_OBJ_G_DIR)/h264/cavlc.o: include/h264/global.h
$(C_OBJ_G_DIR)/h264/cavlc.o: include/h264/vlc.h
$(C_OBJ_G_DIR)/h264/decode.o: include/h264/global.h 
$(C_OBJ_G_DIR)/h264/decode.o: include/h264/parset.h 
$(C_OBJ_G_DIR)/h264/decode.o: include/h264/decode.h 
$(C_OBJ_G_DIR)/h264/decode.o: include/h264/slice.h
$(C_OBJ_G_DIR)/h264/framealloc.o: include/h264/global.h 
$(C_OBJ_G_DIR)/h264/interpred.o: include/h264/global.h 
$(C_OBJ_G_DIR)/h264/interpred.o: include/h264/vlc.h 
$(C_OBJ_G_DIR)/h264/interpred.o: include/h264/mathfunc.h
$(C_OBJ_G_DIR)/h264/mathfunc.o: include/h264/global.h
$(C_OBJ_G_DIR)/h264/mathfunc.o: include/h264/mathfunc.h
$(C_OBJ_G_DIR)/h264/nalu.o: include/h264/global.h
$(C_OBJ_G_DIR)/h264/parset.o: include/h264/global.h
$(C_OBJ_G_DIR)/h264/parset.o: include/h264/framealloc.h
$(C_OBJ_G_DIR)/h264/parset.o: include/h264/vlc.h
$(C_OBJ_G_DIR)/h264/residual.o: include/h264/global.h 
$(C_OBJ_G_DIR)/h264/slice.o: include/h264/global.h
$(C_OBJ_G_DIR)/h264/slice.o: include/h264/intrapred.h
$(C_OBJ_G_DIR)/h264/slice.o: include/h264/vlc.h
$(C_OBJ_G_DIR)/h264/slice.o: include/h264/cavlc.h
$(C_OBJ_G_DIR)/h264/slice.o: include/h264/mathfunc.h
$(C_OBJ_G_DIR)/h264/slice.o: include/h264/residual.h
$(C_OBJ_G_DIR)/h264/slice.o: include/h264/interpred.h
$(C_OBJ_G_DIR)/h264/vlc.o: include/h264/global.h
$(C_OBJ_G_DIR)/h264/do_h264_decode.o: h264/global.h 
$(C_OBJ_G_DIR)/h264/do_h264_decode.o: include/h264/nalu.h 
$(C_OBJ_G_DIR)/h264/do_h264_decode.o: include/h264/decode.h

