# Copyright (c) 2011-2020 Columbia University, System Level Design Group
# SPDX-License-Identifier: Apache-2.0

#V=1
# BEGIN-MODEL-DEPENDENT
MODEL := model
TFLITE_FILE := ./model.tflite

LD_FLAGS :=
VPATH :=
INCDIR :=
CXX_SOURCES :=
LIBS :=

TARGET_ARCH := x86_64

# No external reader for this model
#DATA_DIR := .
#TF_FLAGS := -d $(DATA_DIR)
#INCDIR += -I$(DATA_DIR)/include

# END-MODEL-DEPENDENT

-include ../../common/common.mk
